name: example
description: An example for json_to_csv
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.0.0

dev_dependencies:
  json_to_csv:
    path: ../

json_to_csv:
  files_path: 'assets/json/'
  main_file: 'assets/json/en.json'
  output_file: 'assets/test.csv'
  csv_delimiter: ';'
