name: json_to_csv
description: A tool to convert multiple json files to csv.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  yaml:
  path:

dev_dependencies:
  test:
  lints: ^2.0.0
