name: json_to_csv
description: A tool to convert multiple json files to csv.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/defuncart/json_to_csv

executables:
  json_to_csv:

environment:
  sdk: ^3.0.0

dependencies:
  yaml:
  path:
  args:

dev_dependencies:
  test:
  lints: ^2.0.0
